pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                git update-index --chmod=+x deliver.sh
                /* sh "chmod +rwx ./jenkins/scripts/deliver.sh" */
                sh "./jenkins/scripts/deliver.sh"
            }
        }
    }
}
